name: Teste

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x', 'pypy-3.6', 'pypy-3.7' ]
    name: Python ${{ matrix.python-version }}: teste
    steps:
      - uses: actions/checkout@v2
      - name: Configura python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
        python -m unittest src/tests/test_gerador_relatorio.py
